version: '3'
services:

    db:
        image: mysql:5.7.22
        volumes:
              - ./db/mysql_data:/var/lib/mysql
        ports:
             - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test

    pos_api:
        build: ./pos_api
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        environment:
          DB_HOST_NAME: db
        volumes:
            - "./pos_api:/rails"
        ports:
            - "3000:3000"
        depends_on:
            - db
        links:
            - db

    pos_app:  
        build: ./pos_app
        ports:
            - 13000:13000
        command: [sh, -c, npm run dev]
        volumes:
            - "./pos_app:/app"
            - "/app/node_modules"
        stdin_open: true
        tty: true
