version: '3'
services:

    pos_db:
        image: mysql:5.7.22
        volumes:
              - ./pos_db/mysql_data:/var/lib/mysql
        ports:
             - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test

    pos_api:
        build: ./pos_api
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        environment:
          DB_HOST_NAME: pos_db
        volumes:
            - "./pos_api:/rails"
        ports:
            - "3000:3000"
        depends_on:
            - pos_db
        links:
            - pos_db

    pos_app:  
        build: ./pos_app
        ports:
            - 13000:13000
        command: [sh, -c, npm run dev]
        volumes:
            - "./pos_app:/app"
            - "/app/node_modules"
        stdin_open: true
        tty: true

    reader:
        build: ./reader
        environment:
        - READER_ENV=config.TestingConfig
        ports:
        - "8000:8000"
        volumes:
        - ./reader:/app
    
    tpay_db:
        image: mysql:5.7.22
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./tpay_db/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test
        restart: always
    
    tpay_api:
        build: ./tpay_api
        command: sh -c "./wait-for-it.sh tpay_db:3306; python3 manage.py runserver 0.0.0.0:9000"
        ports:
            - "9000:9000"
        volumes:
            - ./tpay_api:/app
        environment:
            DB_HOST_NAME: tpay_db
        depends_on:
            - tpay_db
